app = "helixismonitor"
primary_region = "arn"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[processes]
  worker = "python mqtt_bridge.py"

[machine]
  auto_stop = false
  auto_start = false
  
[http_service]
  auto_stop_machines = false
  auto_start_machines = true
