-- ============================================================
--  Helix Energy Monitor — Supabase Setup
--  Run this once in the Supabase SQL Editor
-- ============================================================

CREATE TABLE IF NOT EXISTS sensor_readings (
  id         bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz  NOT NULL DEFAULT now(),
  sensor     text         NOT NULL,
  value      float8       NOT NULL,
  topic      text                          -- full MQTT topic, for debugging
);

-- Fast lookups by sensor name
CREATE INDEX IF NOT EXISTS idx_sr_sensor
  ON sensor_readings (sensor);

-- Fast time-range queries (dashboard main query)
CREATE INDEX IF NOT EXISTS idx_sr_created_at
  ON sensor_readings (created_at DESC);

-- Composite: latest-per-sensor queries
CREATE INDEX IF NOT EXISTS idx_sr_sensor_ts
  ON sensor_readings (sensor, created_at DESC);

-- ── Optional: Row-Level Security ─────────────────────────────
-- Enable if you want to lock down the table to service-role key only.
-- ALTER TABLE sensor_readings ENABLE ROW LEVEL SECURITY;

-- ── Optional: auto-purge data older than 1 year ──────────────
-- Requires pg_cron extension (enable in Supabase → Database → Extensions)
-- SELECT cron.schedule(
--   'purge-old-readings',
--   '0 3 * * *',
--   $$DELETE FROM sensor_readings WHERE created_at < now() - INTERVAL '1 year'$$
-- );
